routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::post('selectorg', 'Auth\RegisterController@selectOrg')->name('selectorg');

Route::get('/home', 'HomeController@index');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/clusters/add/{cluster}', 'ClusterController@add');

Route::get('/clusters/requestbaseschool/{user}', 'ClusterController@requestbaseschool');

Route::get('/clusters/addcontract/{school_id}/{cluster_id}', 'ClusterController@addcontract');

Route::post('/clusters/addingprogram/{school_id}/{cluster_id}', 'ClusterController@addingprogram');

Route::get('/clusters/addagreement/{cluster_id}', 'ClusterController@addagreement');

Route::post('/clusters/addingagreement/{cluster_id}', 'ClusterController@addingagreement');

Route::get('/bids/add', 'BidController@add')->name('bids.add');

Route::post('/bids/adding', 'BidController@adding')->name('bids.adding');

Route::get('/bids/createrc/{id}', 'BidController@createrc');

Route::post('/bids/storerc/{id}', 'BidController@storerc');

Route::resource('bids', 'BidController');

Route::resource('clusters', 'ClusterController');

Route::get('/clusters/addoneschool/{baseSchoolId}', 'ClusterController@addoneschool');

Route::delete('/bid/{bid}', 'BidController@delete');

Route::delete('/bid/{bid}/2', 'BidController@delete2');

Route::get('/bids/{bid}/update', 'BidController@show_update');

Route::put('/bids/{bid}/subject-update', 'BidController@update_subject');

Route::put('/bids/{bid}/modul-update', 'BidController@update_modul');

Route::put('/bids/{bid}/hours-update', 'BidController@update_hours');

Route::put('/bids/{bid}/class-update', 'BidController@update_class');

Route::put('/bids/{bid}/amount_of_classes-update', 'BidController@update_amount_of_classes');

Route::put('/bids/{bid}/form_of_education-update', 'BidController@update_form_of_education');

Route::put('/bids/{bid}/form_education_implementation-update', 'BidController@update_form_education_implementation');

Route::put('/bids/{bid}/educational_program-update', 'BidController@update_educational_program');

Route::put('/bids/{bid}/educational_activity-update', 'BidController@update_educational_activity');

Route::put('/bids/{bid}/date_begin-update', 'BidController@update_date_begin');

Route::put('/bids/{bid}/date_end-update', 'BidController@update_date_end');

Route::put('/bids/{bid}/date_end-content', 'BidController@update_content');

Route::delete('/bids/{bid}/back-programs', 'BidController@back_programs');


Route::get('/bids/{bid}/to-archive', 'BidController@show_to_archive');

Route::put('/bids/{bid}/to-archive-send', 'BidController@send_to_archive');

Route::put('/bids/{bid}/from-archive', 'BidController@from_archive');



Route::get('/program/{id}', 'ProgramController@index');

Route::get('/program/add/{program}', 'ProgramController@approve');

Route::post('/program/{id}', 'ProgramController@add');

Route::delete('/program/{program}', 'ProgramController@delete');



Route::get('/schedule/{id}', 'ScheduleController@index');

Route::get('/schedule/add/{schedule}', 'ScheduleController@approve');

Route::post('/schedule/{id}', 'ScheduleController@add');

Route::delete('/schedule/{schedule}', 'ScheduleController@delete');


Route::get('/student/{id}', 'StudentController@index');

// Route::get('/student/add/{student}', 'StudentController@approve');

Route::post('/student/{id}', 'StudentController@add');

Route::delete('/student/{student}', 'StudentController@delete');


Route::get('/agreement/{id}', 'AgreementController@index');

// Route::get('/student/add/{student}', 'StudentController@approve');

Route::post('/agreement/{id}', 'AgreementController@add');

Route::delete('/agreement/{agreement}', 'AgreementController@delete');


Route::get('/agreement-document/create-document/{user_org}/{id}/{program_id}','AgreementDocumentController@create_document_agreement')->name('create_document_agreement');

Route::get('/agreement-document-selected/create-document/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected')->name('create_document_agreement_selected');

Route::get('/agreement-document-selected/create-document2/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected2')->name('create_document_agreement2');

Route::get('/agreement-document-selected/create-document3/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected3')->name('create_document_agreement3');

Route::get('/agreement-document-selected/create-document4/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected4')->name('create_document_agreement4');

Route::get('/agreement-document-selected/create-document-vsu/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected_vsu')->name('create_document_agreement_vsu');

Route::get('/agreement-document-selected/show-document/{user_org}/{program_id}','AgreementDocumentController@show_document_agreement_selected')->name('show_document_agreement_selected');

Route::get('/agreement-document-selected/create-document-vuz/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected_vuz');


Route::post('/instruction/add', 'FileController@add');

Route::post('/public/add2', 'FileController@add2');


Route::get('export', 'ExcelRegionController@export')->name('export');

Route::get('export_mun', 'ExcelMunController@export')->name('export_mun');

Route::get('export_hours', 'ExcelRegionController@months_hours_export')->name('export_hours');

Route::get('export_hours_mun', 'ExcelMunController@months_hours_export')->name('export_hours_mun');

Route::get('export_h', 'ExcelRegionController@m_h_export')->name('export_h');

Route::get('export_h_mun', 'ExcelMunController@m_h_export')->name('export_h_mun');

Route::get('proposed_programs_export', 'ExcelRegionController@proposed_programs_export')->name('proposed_programs_export');

Route::get('selected_programs_export', 'ExcelRegionController@selected_programs_export')->name('selected_programs_export');

Route::get('proposed_programs_export_mun', 'ExcelMunController@proposed_programs_export')->name('proposed_programs_export_mun');

Route::get('selected_programs_export_mun', 'ExcelMunController@selected_programs_export')->name('selected_programs_export_mun');

Route::get('selected_export_hours', 'ExcelRegionController@selected_months_hours_export')->name('selected_export_hours');

Route::get('selected_export_hours_mun', 'ExcelMunController@selected_months_hours_export')->name('selected_export_hours_mun');

Route::get('selected_export_h', 'ExcelRegionController@selected_m_h_export')->name('selected_export_h');

Route::get('selected_export_h_mun', 'ExcelMunController@selected_m_h_export')->name('selected_export_h_mun');

Route::get('export_low_r', 'ExcelRegionController@export_low_r')->name('export_low_r');

Route::get('export_low_f', 'ExcelRegionController@export_low_f')->name('export_low_f');

Route::get('export_low_r_mun', 'ExcelMunController@export_low_r')->name('export_low_r_mun');

Route::get('export_low_f_mun', 'ExcelMunController@export_low_f')->name('export_low_f_mun');


Route::post('/region-clusters', 'RegionClusterController@store');

Route::get('/region-clusters/create', 'RegionClusterController@create');

Route::post('/region-clusters/addingprogram/{id}', 'RegionClusterController@addingprogram');

Route::get('/region-clusters/addcontract/{id}', 'RegionClusterController@addcontract');

Route::get('/user/approve/{user_id}', 'UserController@approve');

Route::get('/user/reject/{user_id}', 'UserController@reject');


Route::get('/users/{orgtype}/org-list', 'UserController@show_users')->name('org_list');

Route::get('/users/{user_org}/show-org', 'UserController@show_user');

Route::put('/users/{user_org}/update-inn', 'UserController@update_inn');

Route::put('/users/{user_org}/update-add', 'UserController@update_add');

Route::put('/users/{user_org}/update-tel', 'UserController@update_tel');

Route::put('/users/{user_org}/update-email_real', 'UserController@update_email_real');

Route::put('/users/{user_org}/update-web', 'UserController@update_web');

Route::put('/users/{user_org}/update-shnor', 'UserController@update_shnor');

Route::put('/users/{user_org}/update-type', 'UserController@update_type');

Route::put('/users/{user_org}/update-zone', 'UserController@update_zone');

Route::put('/users/{user_org}/update-kpp', 'UserController@update_kpp');

Route::put('/users/{user_org}/update-ogrn', 'UserController@update_ogrn');

Route::put('/users/{user_org}/update-kbk', 'UserController@update_kbk');

Route::put('/users/{user_org}/update-ikz', 'UserController@update_ikz');

Route::put('/users/{user_org}/update-punkt', 'UserController@update_punkt');

Route::put('/users/{user_org}/update-bik', 'UserController@update_bik');

Route::put('/users/{user_org}/update-okpo', 'UserController@update_okpo');

Route::put('/users/{user_org}/update-oktmo', 'UserController@update_oktmo');

Route::put('/users/{user_org}/update-single_treasury_account', 'UserController@update_single_treasury_account');

Route::put('/users/{user_org}/update-treasury_account', 'UserController@update_treasury_account');

Route::put('/users/{user_org}/update-single_treasury_account_type', 'UserController@update_single_treasury_account_type');

Route::put('/users/{user_org}/update-treasury_account_type', 'UserController@update_treasury_account_type');

Route::put('/users/{user_org}/update-bank', 'UserController@update_bank');

app/Cluster.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cluster extends Model
{
    protected $table = 'clusters';

    protected $fillable = ['user_id', 'district_id', 'schools', 'status', 'agreement'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function district()
    {
        return $this->belongsTo(District::class);
    }

    public function getBids()
    {
        if ($bids = Bid::where('cluster_id', $this->id)->get()) {
            return $bids;
        } else return false;
    }
}

app/Http/Controllers/ClusterController.php
<?php

namespace App\Http\Controllers;

use App\Cluster;
use App\District;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClusterController extends Controller
{
    private const CLUSTER_APPROVED = 1;
    private const CLUSTER_SERTIFIED = 2;
    private const RECIPIENT_SCHOOL = 0;
    private const REGIONAL_COORD = 1;
    private const BASE_SCHOOL = 2;
    private const REQUEST_BASE_SCHOOL = 5;

    public function add(Cluster $cluster)
    {
        $cluster->status = self::CLUSTER_SERTIFIED;
        $cluster->save();

        $user = $cluster->user;
        $user->status = self::BASE_SCHOOL;
        $user->save();

        return redirect('/clusters')->with('success', 'Заявка на кластер добавлена!');
    }

    public function requestbaseschool($id)
    {
        $user = User::where('id', $id)->first();
        $user->status = self::REQUEST_BASE_SCHOOL;

        $user->save();

        return redirect('/');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->id === self::REGIONAL_COORD) {
            $clusters = Cluster::all();
            return view('clusters.index', compact('clusters'));
        } else return redirect('/');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $district = $user->getDistrict;

        return view('clusters.create', compact(['user', 'district']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        $district = $user->getDistrict;

        $files = [];

        foreach ($request->post('schools') as $id) {
            $school = User::where('id', $id)->first();
            $new_file['school_name'] = $school->fullname;
            $new_file['school_id'] = $id;
            array_push($files, $new_file);
        }

        $files = json_encode($files);

        $cluster = new Cluster([
            'user_id' => $user->id,
            'district_id' => $district->id,
            'schools' => $files,
            'status' => self::CLUSTER_APPROVED,
        ]);

        $cluster->save();

        $user->status = self::BASE_SCHOOL;
        $user->save();

        return redirect('/')->with('success', 'Заявка на кластер добавлена!');
    }

    public function addcontract($school_id, $cluster_id)
    {
        return view('clusters.addcontract', ['school_id' => $school_id, 'cluster_id' => $cluster_id]);
    }

    public function addingprogram(Request $request, $school_id, $cluster_id)
    {
        if($request->hasFile('contract')) {
            $file = $request->file('contract');
            $file_name = $school_id . time() . '.' . $request->contract->extension();
            $file->move(public_path() . '/files/contracts/', $file_name);

            $cluster = Cluster::where('id', $cluster_id)->first();
            $schools = json_decode($cluster->schools, true);
            foreach ($schools as $key => $school) {
                if ($school_id == $school['school_id']){
                    $k = $key;
                }
            }
            $schools[$k]['file_name'] = $file_name;
            $cluster->schools = json_encode($schools);

            $cluster->save();

            return redirect('/');
        }

        return redirect('/');
    }

    public function addagreement($cluster_id)
    {
        return view('clusters.addagreement', ['cluster_id' => $cluster_id]);
    }

    public function addingagreement(Request $request, $cluster_id)
    {
        if($request->hasFile('agreement')) {
            $file = $request->file('agreement');
            $file_name = $cluster_id . time() . '.' . $request->agreement->extension();
            $file->move(public_path() . '/files/agreements/', $file_name);

            $cluster = Cluster::where('id', $cluster_id)->first();
            $cluster->agreement = $file_name;

            $cluster->save();

            return redirect('/');
        }
    }

    public function addoneschool($baseSchoolId, Request $request)
    {
        if ($request->get('schoolid')) {
            $schoolId = $request->get('schoolid');
            $cluster = Cluster::where('user_id', $baseSchoolId)->first();
            $schoolsInCluster = json_decode($cluster->schools, true);
            $schoolName = User::where('id', $schoolId)->first()->fullname;
            $arr["school_name"] = $schoolName;
            $arr["school_id"] = $schoolId;
            array_push($schoolsInCluster, $arr);
            $cluster->schools = $schoolsInCluster;

            $cluster->save();

        }
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cluster  $cluster
     * @return \Illuminate\Http\Response
     */
    public function show(Cluster $cluster)
    {
        return view('clusters.show',compact('cluster'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cluster  $cluster
     * @return \Illuminate\Http\Response
     */

    public function edit(Cluster $cluster)
    {
        if (Auth::user()->id === 1) {
            return view('clusters.edit', compact('cluster'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cluster  $cluster
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cluster $cluster)
    {
        $request->validate([
            'date_of_cluster' => 'required',
            'status' => 'required',
        ]);

        $cluster->update($request->all());


        return redirect()->route('home')
            ->with('success','Кластер изменен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cluster $cluster
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Cluster $cluster)
    {
        $user = $cluster->user;
        $user->status = self::RECIPIENT_SCHOOL;

        $cluster->delete();

        $user->save();

        return redirect()->route('clusters.index')
            ->with('success','Кластер удален');
    }
}

resources/views/clusters/addagreement.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h3>Добавить соглашение</h3>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="/clusters/addingagreement/{{ $cluster_id }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="agreement">
                            <label class="custom-file-label">Загрузить</label>
                        </div>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Добавить соглашение</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/clusters/addcontract.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h3>Добавить договор</h3>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="/clusters/addingprogram/{{ $school_id }}/{{ $cluster_id }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="contract">
                            <label class="custom-file-label">Загрузить</label>
                        </div>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Добавить договор</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/clusters/all.blade.php
@extends('layouts.app')

@section('content')
@if (Auth::user() && (Auth::user()->status == 1 || Auth::user()->status == 10))
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-header">
                        @if(Auth::user()->status == 1)
                        <h2>Региональный координатор</h2>
                        @elseif(Auth::user()->status == 10)
                        <h2>Муниципальный координатор</h2>
                        @endif

                        @if(Auth::user()->status == 1)
                        <ul class="list-group">
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item flex-fill">
                                    Выгрузка всех заявок:
                                    <a class="btn btn-outline-dark" href="{{ route('export') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Выгрузка предложенных программ:
                                    <a class="btn btn-outline-dark" href="{{ route('proposed_programs_export') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item flex-fill">
                                    Список действующих организаций Воронежской области:
                                    <a class="btn btn-outline-dark" href="{{ route('org_list') }}">Организации</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Выгрузка взятых предложеннных программ:
                                    <a class="btn btn-outline-dark" href="{{ route('selected_programs_export') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item flex-fill">
                                    Кол-во часов по месяцам:
                                    <a class="btn btn-outline-dark" href="{{ route('export_hours') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Кол-во часов по месяцам (по предложенным программам):
                                    <a class="btn btn-outline-dark" href="{{ route('selected_export_hours') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item flex-fill">
                                    Кол-во часов по месяцам у базовых организаций (2022-2023):
                                    <a class="btn btn-outline-dark" href="{{ route('export_h') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Кол-во часов по месяцам у базовых организаций (2022-2023) (по предложенным программам):
                                    <a class="btn btn-outline-dark" href="{{ route('selected_export_h') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item flex-fill">
                                    Выгрузка заявок организаций с низкими результатами (региональный уровень):
                                    <a class="btn btn-outline-dark" href="{{ route('export_low_r') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Выгрузка заявок организаций с низкими результатами (федеральный уровень):
                                    <a class="btn btn-outline-dark" href="{{ route('export_low_f') }}">Export</a>
                                </li>
                            </ul>

                        </ul>

                        @elseif(Auth::user()->status == 10)
                        <ul class="list-group">
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item">
                                    Выгрузка заявок муниципалитета:
                                    <a class="btn btn-outline-dark" href="{{ route('export_mun') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Выгрузка предложенных программ:
                                    <a class="btn btn-outline-dark" href="{{ route('proposed_programs_export_mun') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item">
                                    Список действующих организаций муниципалитета:
                                    <a class="btn btn-outline-dark" href="/users/{{ Auth::user()->getDistrict->id }}/all/org-list-mun">Организации</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Выгрузка взятых предложеннных программ:
                                    <a class="btn btn-outline-dark" href="{{ route('selected_programs_export_mun') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item">
                                    Кол-во часов по месяцам:
                                    <a class="btn btn-outline-dark" href="{{ route('export_hours_mun') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Кол-во часов по месяцам (по предложенным программам):
                                    <a class="btn btn-outline-dark" href="{{ route('selected_export_hours_mun') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item">
                                    Кол-во часов по месяцам у базовых организаций (2022-2023):
                                    <a class="btn btn-outline-dark" href="{{ route('export_h_mun') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Кол-во часов по месяцам у базовых организаций (2022-2023) (по предложенным программам):
                                    <a class="btn btn-outline-dark" href="{{ route('selected_export_h_mun') }}">Export</a>
                                </li>
                            </ul>
                            <ul class="list-group list-group-horizontal">
                                <li class="list-group-item flex-fill">
                                    Выгрузка заявок организаций с низкими результатами (региональный уровень):
                                    <a class="btn btn-outline-dark" href="{{ route('export_low_r_mun') }}">Export</a>
                                </li>
                                <li class="list-group-item flex-fill">
                                    Выгрузка заявок организаций с низкими результатами (федеральный уровень):
                                    <a class="btn btn-outline-dark" href="{{ route('export_low_f_mun') }}">Export</a>
                                </li>
                            </ul>
                        </ul>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endif
@endsection

resources/views/clusters/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h3 class="display-5">{{ $user->fullname }}</h3>
            
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br/>
                @endif
                <form method="post" action="{{ route('clusters.store') }}" enctype="multipart/form-data">
                    @csrf
                    <h4 align="center">Выберите образовательные организации в образовательный кластер</h4>
                    <p class="alert alert-info" role="alert">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-exclamation-octagon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.54.146A.5.5 0 0 1 4.893 0h6.214a.5.5 0 0 1 .353.146l4.394 4.394a.5.5 0 0 1 .146.353v6.214a.5.5 0 0 1-.146.353l-4.394 4.394a.5.5 0 0 1-.353.146H4.893a.5.5 0 0 1-.353-.146L.146 11.46A.5.5 0 0 1 0 11.107V4.893a.5.5 0 0 1 .146-.353L4.54.146zM5.1 1L1 5.1v5.8L5.1 15h5.8l4.1-4.1V5.1L10.9 1H5.1z"/>
                            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                        </svg> - школы с низкими показателями
                    </p>
                    @foreach($district->users as $school)
                        @if (($school->id !== $user->id) && ($school->fullname != ''))
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="schools[]" value="{{ $school->id }}">
                                        <label class="form-check-label">
                                            {{ $school->fullname }}
                                            @if ($school->status == 7)
                                                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-exclamation-octagon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" d="M4.54.146A.5.5 0 0 1 4.893 0h6.214a.5.5 0 0 1 .353.146l4.394 4.394a.5.5 0 0 1 .146.353v6.214a.5.5 0 0 1-.146.353l-4.394 4.394a.5.5 0 0 1-.353.146H4.893a.5.5 0 0 1-.353-.146L.146 11.46A.5.5 0 0 1 0 11.107V4.893a.5.5 0 0 1 .146-.353L4.54.146zM5.1 1L1 5.1v5.8L5.1 15h5.8l4.1-4.1V5.1L10.9 1H5.1z"/>
                                                    <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                                                </svg>
                                            @endif
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endif
                    @endforeach
                    <br>
                    <button type="submit" class="btn btn-outline-primary btn-lg">Подать заявку на создание кластера</button>
                </form>
            </div>
        </div>
    </div>
@endsection