routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::post('selectorg', 'Auth\RegisterController@selectOrg')->name('selectorg');

Route::get('/home', 'HomeController@index');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/clusters/add/{cluster}', 'ClusterController@add');

Route::get('/clusters/requestbaseschool/{user}', 'ClusterController@requestbaseschool');

Route::get('/clusters/addcontract/{school_id}/{cluster_id}', 'ClusterController@addcontract');

Route::post('/clusters/addingprogram/{school_id}/{cluster_id}', 'ClusterController@addingprogram');

Route::get('/clusters/addagreement/{cluster_id}', 'ClusterController@addagreement');

Route::post('/clusters/addingagreement/{cluster_id}', 'ClusterController@addingagreement');

Route::get('/bids/add', 'BidController@add')->name('bids.add');

Route::post('/bids/adding', 'BidController@adding')->name('bids.adding');

Route::get('/bids/createrc/{id}', 'BidController@createrc');

Route::post('/bids/storerc/{id}', 'BidController@storerc');

Route::resource('bids', 'BidController');

Route::resource('clusters', 'ClusterController');

Route::get('/clusters/addoneschool/{baseSchoolId}', 'ClusterController@addoneschool');

Route::delete('/bid/{bid}', 'BidController@delete');

Route::delete('/bid/{bid}/2', 'BidController@delete2');

Route::get('/bids/{bid}/update', 'BidController@show_update');

Route::put('/bids/{bid}/subject-update', 'BidController@update_subject');

Route::put('/bids/{bid}/modul-update', 'BidController@update_modul');

Route::put('/bids/{bid}/hours-update', 'BidController@update_hours');

Route::put('/bids/{bid}/class-update', 'BidController@update_class');

Route::put('/bids/{bid}/amount_of_classes-update', 'BidController@update_amount_of_classes');

Route::put('/bids/{bid}/form_of_education-update', 'BidController@update_form_of_education');

Route::put('/bids/{bid}/form_education_implementation-update', 'BidController@update_form_education_implementation');

Route::put('/bids/{bid}/educational_program-update', 'BidController@update_educational_program');

Route::put('/bids/{bid}/educational_activity-update', 'BidController@update_educational_activity');

Route::put('/bids/{bid}/date_begin-update', 'BidController@update_date_begin');

Route::put('/bids/{bid}/date_end-update', 'BidController@update_date_end');

Route::put('/bids/{bid}/date_end-content', 'BidController@update_content');

Route::delete('/bids/{bid}/back-programs', 'BidController@back_programs');


Route::get('/bids/{bid}/to-archive', 'BidController@show_to_archive');

Route::put('/bids/{bid}/to-archive-send', 'BidController@send_to_archive');

Route::put('/bids/{bid}/from-archive', 'BidController@from_archive');



Route::get('/program/{id}', 'ProgramController@index');

Route::get('/program/add/{program}', 'ProgramController@approve');

Route::post('/program/{id}', 'ProgramController@add');

Route::delete('/program/{program}', 'ProgramController@delete');



Route::get('/schedule/{id}', 'ScheduleController@index');

Route::get('/schedule/add/{schedule}', 'ScheduleController@approve');

Route::post('/schedule/{id}', 'ScheduleController@add');

Route::delete('/schedule/{schedule}', 'ScheduleController@delete');


Route::get('/student/{id}', 'StudentController@index');

// Route::get('/student/add/{student}', 'StudentController@approve');

Route::post('/student/{id}', 'StudentController@add');

Route::delete('/student/{student}', 'StudentController@delete');


Route::get('/agreement/{id}', 'AgreementController@index');

// Route::get('/student/add/{student}', 'StudentController@approve');

Route::post('/agreement/{id}', 'AgreementController@add');

Route::delete('/agreement/{agreement}', 'AgreementController@delete');


Route::get('/agreement-document/create-document/{user_org}/{id}/{program_id}','AgreementDocumentController@create_document_agreement')->name('create_document_agreement');

Route::get('/agreement-document-selected/create-document/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected')->name('create_document_agreement_selected');

Route::get('/agreement-document-selected/create-document2/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected2')->name('create_document_agreement2');

Route::get('/agreement-document-selected/create-document3/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected3')->name('create_document_agreement3');

Route::get('/agreement-document-selected/create-document4/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected4')->name('create_document_agreement4');

Route::get('/agreement-document-selected/create-document-vsu/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected_vsu')->name('create_document_agreement_vsu');

Route::get('/agreement-document-selected/show-document/{user_org}/{program_id}','AgreementDocumentController@show_document_agreement_selected')->name('show_document_agreement_selected');

Route::get('/agreement-document-selected/create-document-vuz/{user_org}/{program_id}','AgreementDocumentController@create_document_agreement_selected_vuz');


Route::post('/instruction/add', 'FileController@add');

Route::post('/public/add2', 'FileController@add2');


Route::get('export', 'ExcelRegionController@export')->name('export');

Route::get('export_mun', 'ExcelMunController@export')->name('export_mun');

Route::get('export_hours', 'ExcelRegionController@months_hours_export')->name('export_hours');

Route::get('export_hours_mun', 'ExcelMunController@months_hours_export')->name('export_hours_mun');

Route::get('export_h', 'ExcelRegionController@m_h_export')->name('export_h');

Route::get('export_h_mun', 'ExcelMunController@m_h_export')->name('export_h_mun');

Route::get('proposed_programs_export', 'ExcelRegionController@proposed_programs_export')->name('proposed_programs_export');

Route::get('selected_programs_export', 'ExcelRegionController@selected_programs_export')->name('selected_programs_export');

Route::get('proposed_programs_export_mun', 'ExcelMunController@proposed_programs_export')->name('proposed_programs_export_mun');

Route::get('selected_programs_export_mun', 'ExcelMunController@selected_programs_export')->name('selected_programs_export_mun');

Route::get('selected_export_hours', 'ExcelRegionController@selected_months_hours_export')->name('selected_export_hours');

Route::get('selected_export_hours_mun', 'ExcelMunController@selected_months_hours_export')->name('selected_export_hours_mun');

Route::get('selected_export_h', 'ExcelRegionController@selected_m_h_export')->name('selected_export_h');

Route::get('selected_export_h_mun', 'ExcelMunController@selected_m_h_export')->name('selected_export_h_mun');

Route::get('export_low_r', 'ExcelRegionController@export_low_r')->name('export_low_r');

Route::get('export_low_f', 'ExcelRegionController@export_low_f')->name('export_low_f');

Route::get('export_low_r_mun', 'ExcelMunController@export_low_r')->name('export_low_r_mun');

Route::get('export_low_f_mun', 'ExcelMunController@export_low_f')->name('export_low_f_mun');


Route::post('/region-clusters', 'RegionClusterController@store');

Route::get('/region-clusters/create', 'RegionClusterController@create');

Route::post('/region-clusters/addingprogram/{id}', 'RegionClusterController@addingprogram');

Route::get('/region-clusters/addcontract/{id}', 'RegionClusterController@addcontract');

Route::get('/user/approve/{user_id}', 'UserController@approve');

Route::get('/user/reject/{user_id}', 'UserController@reject');


Route::get('/users/{orgtype}/org-list', 'UserController@show_users')->name('org_list');

Route::get('/users/{user_org}/show-org', 'UserController@show_user');

Route::put('/users/{user_org}/update-inn', 'UserController@update_inn');

Route::put('/users/{user_org}/update-add', 'UserController@update_add');

Route::put('/users/{user_org}/update-tel', 'UserController@update_tel');

Route::put('/users/{user_org}/update-email_real', 'UserController@update_email_real');

Route::put('/users/{user_org}/update-web', 'UserController@update_web');

Route::put('/users/{user_org}/update-shnor', 'UserController@update_shnor');

Route::put('/users/{user_org}/update-type', 'UserController@update_type');

Route::put('/users/{user_org}/update-zone', 'UserController@update_zone');

Route::put('/users/{user_org}/update-kpp', 'UserController@update_kpp');

Route::put('/users/{user_org}/update-ogrn', 'UserController@update_ogrn');

Route::put('/users/{user_org}/update-kbk', 'UserController@update_kbk');

Route::put('/users/{user_org}/update-ikz', 'UserController@update_ikz');

Route::put('/users/{user_org}/update-punkt', 'UserController@update_punkt');

Route::put('/users/{user_org}/update-bik', 'UserController@update_bik');

Route::put('/users/{user_org}/update-okpo', 'UserController@update_okpo');

Route::put('/users/{user_org}/update-oktmo', 'UserController@update_oktmo');

Route::put('/users/{user_org}/update-single_treasury_account', 'UserController@update_single_treasury_account');

Route::put('/users/{user_org}/update-treasury_account', 'UserController@update_treasury_account');

Route::put('/users/{user_org}/update-single_treasury_account_type', 'UserController@update_single_treasury_account_type');

Route::put('/users/{user_org}/update-treasury_account_type', 'UserController@update_treasury_account_type');

Route::put('/users/{user_org}/update-bank', 'UserController@update_bank');

app/Bid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bid extends Model
{
    protected $table = 'bids';

    protected $fillable = ['subject', 'class', 'content', 'user_id', 'modul', 'hours', 'educational_program',
        'educational_activity', 'form_of_education', 'form_education_implementation', 'date_begin', 'date_end',
         'rc_cluster_id', 'archive', 'amount_of_classes'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function program()
    {
        return $this->hasOne(Program::class);
    }

    public function programs()
    {
        if ($programs = Program::where('bid_id', $this->id)->get()) {
            return $programs;
        } else return false;

    }

    public function getStatus()
    {
        switch ($this->status) {
            case 0: return '<div class="alert alert-warning" role="alert">Рассмотрение</div>';
            case 1: return '<div class="alert alert-success" role="alert">Одобрена</div>';
            case 2: return '<div class="alert alert-danger" role="alert">Отклонена</div>';
            case 3: return '<div class="alert alert-info" role="alert">Своя программа</div>';

            case 9: return '<div class="alert alert-info" role="alert">Поступило предложение</div>';
        }
    }

    public function getStatus2()
    {
        switch ($this->status) {
            case 0: return 'Рассмотрение';
            case 1: return 'Одобрена';
            case 2: return 'Отклонена';

            case 9: return 'Поступило предложение';
        }
    }

    public function getClasses()
    {
        $classes = unserialize($this->class);
        $str = "";
        foreach ($classes as $class) {
            $str .= $class . ", ";
        }

        return substr($str, 0, -2);
    }

    public function getEducationalPrograms()
    {
        $educational_programs = unserialize($this->educational_program);
        $str = "";
        if($educational_programs != NULL) {
            foreach ($educational_programs as $educational_program) {
                $str .= $educational_program . ", ";
            }
            return substr($str, 0, -2);
        }
        else return '';
    }

    public function getEducationalActivities()
    {
        $educational_activities = unserialize($this->educational_activity);
        $str = "";
        if($educational_activities != NULL) {
            foreach ($educational_activities as $educational_activity) {
                $str .= $educational_activity . ", ";
            }
            return substr($str, 0, -2);
        }
        else return '';

    }

    public function getDataBegin()
    {
        $date = $this->date_begin;
        if($date !== NULL) {
            $year = substr($date, 0, -6);
            $month = substr($date, 5, -3);
            $day = substr($date, -2);
            $date_begin = $day . "-" . $month . "-" . $year;
            return $date_begin;
        }
        else return '';
    }

    public function getDataEnd()
    {
        $date = $this->date_end;
        if($date !== NULL) {
            $year = substr($date, 0, -6);
            $month = substr($date, 5, -3);
            $day = substr($date, -2);
            $date_end = $day . "-" . $month . "-" . $year;
            return $date_end;
        }
        else return '';
    }


    function getAcademicYear($startDate) {
        $month = date('m', strtotime($startDate));
        $year = date('Y', strtotime($startDate));
    
        if ($month >= 9) {
            return $year . '-' . ($year + 1);
        } else {
            return ($year - 1) . '-' . $year;
        }
    }
}

resources/views/bids/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h3>Добавить предмет/курс </h3>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('bids.store') }}" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="class">Класс/группа:</label>
                        <select class="form-control" name="class[]" id="selectid">
                            <option value=""></option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="смешанная группа" id="smesh">смешанная группа</option>
                        </select>
                    </div>

                    <ul class="list-group" id="mix" style="margin:0 auto; display:none;">
                        <label for="class">Выберите классы для смешанной группы:</label>
                        <li class="list-group-item">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="1">
                                <label class="form-check-label">1</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="2">
                                <label class="form-check-label">2</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="3">
                                <label class="form-check-label">3</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="4">
                                <label class="form-check-label">4</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="5">
                                <label class="form-check-label">5</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="6">
                                <label class="form-check-label">6</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="7">
                                <label class="form-check-label">7</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="8">
                                <label class="form-check-label">8</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="9">
                                <label class="form-check-label">9</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="10">
                                <label class="form-check-label">10</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="class[]" type="checkbox" value="11">
                                <label class="form-check-label">11</label>
                            </div>
                        </li>
                    </ul>

                    <div class="form-group">
                        <label for="amount_of_classes">Количество классов/групп:</label>
                        <input type="text" class="form-control" name="amount_of_classes"/>
                    </div>


                    <div class="form-group">
                        <label for="subject">Предмет/курс:</label>
                        <input type="text" class="form-control" name="subject"/>
                    </div>

                    <div class="form-group">
                        <label for="modul">Раздел/модуль:</label>
                        <input type="text" class="form-control" name="modul"/>
                    </div>

                    <div class="form-group">
                        <label for="modul">Кол-во часов:</label>
                        <input type="number" class="form-control" name="hours"/>
                        <small>Введите число</small>
                    </div>

                    <div class="form-group">
                        <label for="educational_program">Образовательная программа:</label>
                        <select class="form-control" name="educational_program[]">
                            <option value=""></option>
                            <option value="основная">основная</option>

                            <option value="дополнительная">дополнительная</option>
                        </select>
                    </div>


                    <div class="form-group">
                        <label for="educational_activity">Образовательная деятельность:</label>
                        <select class="form-control" name="educational_activity[]">
                            <option value=""></option>
                            <option value="урочная">урочная</option>

                            <option value="внеурочная">внеурочная</option>
                        </select>
                    </div>


                    <div class="form-group">
                        <label for="form_of_education">Форма обучения:</label>
                        <select class="form-control" name="form_of_education">
                            <option value=""></option>
                            <option value="очная">очная</option>
                            <option value="очно-заочная">очно-заочная</option>
                            <option value="заочная">заочная</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="form_education_implementation">Условия реализации образовательных программ:</label>
                        <select class="form-control" name="form_education_implementation">
                            <option value=""></option>
                            <option value="с использованием дистанционных образовательных технологий, электронного обучения">с использованием дистанционных образовательных технологий, электронного обучения</option>

                            <option value="трансфер детей до организации">трансфер детей до организации</option>
                            <option value="трансфер + дистанционные технологии">трансфер + дистанционные технологии</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="date_begin">Начало:</label>
                        <input type="date" class="form-control" data-date-format="dd/mm/yyyy" name="date_begin"/>
                        <small class="form-text text-muted">нажмите на значок справа</small>
                    </div>

                    <div class="form-group">
                        <label for="date_end">Конец:</label>
                        <input type="date" class="form-control" data-date-format="dd/mm/yyyy" name="date_end"/>
                        <small class="form-text text-muted">нажмите на значок справа</small>
                    </div>

                    <div class="form-group">
                        <label for="content">Комментарий:</label>
                        <textarea class="form-control" name="content"></textarea>
                    </div>

                    <br>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </form>
            </div>
        </div>
    </div>


    <script>
        $(function() {
            $("#selectid").change(function() {
                if ($("#smesh").is(":selected")) {
                    $("#mix").show();
                }
                else {
                    $("#mix").hide();
                }
            }).trigger('change');
        });

        $('select[name="educational_program"]').on('change', function() {
            if ($(this).val() === 'дополнительная') {
                $('select[name="educational_activity"] option:not([value=""])').remove();
            }
        });
    </script>
@endsection

resources/views/bids/createrc.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h3>Добавить предмет/курс </h3>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="/bids/storerc/{{ $id }}" enctype="multipart/form-data">
                    @csrf

                    <label for="class">Класс/группа</label><br>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="1">
                        <label class="form-check-label">1</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="2">
                        <label class="form-check-label">2</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="3">
                        <label class="form-check-label">3</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="4">
                        <label class="form-check-label">4</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="5">
                        <label class="form-check-label">5</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="6">
                        <label class="form-check-label">6</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="7">
                        <label class="form-check-label">7</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="8">
                        <label class="form-check-label">8</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="9">
                        <label class="form-check-label">9</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="10">
                        <label class="form-check-label">10</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="11">
                        <label class="form-check-label">11</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="class[]" type="checkbox" value="смешанная группа">
                        <label class="form-check-label">смешанная группа</label>
                    </div>

                    <div class="form-group">
                        <label for="subject">Предмет/курс:</label>
                        <input type="text" class="form-control" name="subject"/>
                    </div>

                    <div class="form-group">
                        <label for="modul">Раздел/модуль:</label>
                        <input type="text" class="form-control" name="modul"/>
                    </div>

                    <div class="form-group">
                        <label for="form_of_education">Форма обучения</label>
                        <select class="form-control" name="form_of_education">
                            <option value=""></option>
                            <option value="очная">очная</option>
                            <option value="очно-заочная">очно-заочная</option>
                            <option value="заочная">заочная</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="form_education_implementation">Условия реализации образовательных программ</label>
                        <select class="form-control" name="form_education_implementation">
                            <option value=""></option>
                            <option value="с использованием дистанционных образовательных технологий, электронного обучения">с использованием дистанционных образовательных технологий, электронного обучения</option>

                            <option value="трансфер детей до организации">трансфер детей до организации</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="content">Комментарий:</label>
                        <textarea class="form-control" name="content"></textarea>
                    </div>

                    <br>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/bids/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <h2>{{ $bids[0]->user->fullname }}</h2>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>Класс</td>
                    <td>Предмет/курс</td>
                    <td>Раздел/модуль</td>
                    <td>Форма обучения</td>
                    <td>Условия реализации обучения</td>
                    <td>Комментарий</td>
                    <td>Статус</td>
                </tr>
                </thead>
            @foreach($bids as $bid)
                    <tr>
                        <td>{{ $bid->getClasses() }}</td>
                        <td>{{ $bid->subject }}</td>
                        <td>{{ $bid->modul }}</td>
                        <td>{{ $bid->form_of_education }}</td>
                        <td>{{ $bid->form_education_implementation }}</td>
                        <td>{{ $bid->content }}</td>
                        <td>{!! $bid->getStatus() !!}</td>
                    </tr>
            @endforeach
            </table>
        </div>
    </div>
@endsection